### PR TITLE
iOS 15 and rootless support

### PR DESCRIPTION
**Pull request by PoomSmart**

### CODE REVIEW

**Comment by NSExceptional** [comment]
Can we split the unrelated changes out into a separate PR? Also I want a linear history kept, so you need to rebase your commits onto `origin/master` instead of merging. I can take care of all that if you want, Tower makes it pretty easy, just lmk

**Comment by NSExceptional** [comment]
Also, thanks for the PR :)

**Comment by PoomSmart** [comment]
@NSExceptional I guess my fork is a little messed up. You can use your Tower tool to fix it up I think.

Also, squashing merging won't help?

**Comment by NSExceptional** [comment]
It would except that I want the changes split into two separate commits 😅 I'll do it tomorrow

**Comment by L1ghtmann** [comment]
Any update on this?

**Comment by PoomSmart** [comment]
Up to him.

**Comment by NyaMisty** [comment]
probably we should merge this?

**Comment by NSExceptional** [comment]
Hey everyone, I apologize for my inactivity this year. It's been a hard year for me. Two breakups and one extremely toxic relationship. Also I've been swamped at work while trying to buy a house at the same time.

I'm hoping next year will be better. My manager is going to give us a lot of PTO at some point before summer. @PoomSmart do you still have these changes on your fork somewhere?

**Comment by NyaMisty** [comment]
I've updated @PoomSmart's fork here here #44

**Comment by PoomSmart** [comment]
^

**Pull request closed without merging**
